"""create movie tables

Revision ID: c34025e1aff2
Revises: 
Create Date: 2026-04-04 08:50:13.595141

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c34025e1aff2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('genre', sa.String(length=20), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('synopsis', sa.Text(), nullable=False),
    sa.Column('director', sa.String(length=100), nullable=True),
    sa.Column('lead_actor', sa.String(length=100), nullable=True),
    sa.Column('recommended_for', sa.String(length=20), nullable=True),
    sa.CheckConstraint("genre IN ('action', 'comedy', 'drama', 'sci-fi', 'thriller', 'horror', 'romance')", name='ck_movies_genre'),
    sa.CheckConstraint("recommended_for IS NULL OR recommended_for IN ('family', 'teens', 'adults')", name='ck_movies_recommended_for'),
    sa.CheckConstraint('char_length(synopsis) BETWEEN 10 AND 500', name='ck_movies_synopsis_length'),
    sa.CheckConstraint('char_length(title) BETWEEN 1 AND 100', name='ck_movies_title_length'),
    sa.CheckConstraint('rating BETWEEN 0.0 AND 10.0', name='ck_movies_rating'),
    sa.CheckConstraint('year BETWEEN 1900 AND 2025', name='ck_movies_year'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movies_genre'), 'movies', ['genre'], unique=False)
    op.create_index(op.f('ix_movies_rating'), 'movies', ['rating'], unique=False)
    op.create_index(op.f('ix_movies_recommended_for'), 'movies', ['recommended_for'], unique=False)
    op.create_index(op.f('ix_movies_title'), 'movies', ['title'], unique=False)
    op.create_index(op.f('ix_movies_year'), 'movies', ['year'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_movies_year'), table_name='movies')
    op.drop_index(op.f('ix_movies_title'), table_name='movies')
    op.drop_index(op.f('ix_movies_recommended_for'), table_name='movies')
    op.drop_index(op.f('ix_movies_rating'), table_name='movies')
    op.drop_index(op.f('ix_movies_genre'), table_name='movies')
    op.drop_table('movies')
    # ### end Alembic commands ###
